### PR TITLE
chore: biw test-fixes, entity images for smart item component and Builder In World Controller refactor

### LINKED ISSUE #1991: Thumbnail Entity URL (Unity)

### LINKED ISSUE #1996: Smart items code generation

### LINKED ISSUE #1999: Smart Items in dropdown
In the smart item entity dropdown box, we need small thumbnails that show how each entity looks like.

### LINKED ISSUE #2038: How to handle entity images for smart item entity parameter? (Asset promiser raw image)

### LINKED ISSUE #2045: BuilderInWorldController refactor: segregate responsibilities
`BuilderInWorldController` has gotten too big. We should move many responsibilities outside of this class.

- [x] Modes Controller
- [x] Publish conditions
- [x] Outliner checker
- [x] General input handler
- [x] Floor handler
- [x] `SceneObject` creation

### LINKED ISSUE #2046: BuilderInWorldController: Publish conditions (Check with interval)
Move responsibility outside of BuilderInWorldController

### LINKED ISSUE #2047: BuilderInWorldController: Outliner checker (Check with interval)
Move responsibility outside of BuilderInWorldController

### LINKED ISSUE #2048: BuilderInWorldController: General input handler
Move responsibility outside of BuilderInWorldController

### LINKED ISSUE #2049: BuilderInWorldController: Floor handler
Move responsibility outside of BuilderInWorldController

### LINKED ISSUE #2055: Test Undo/Redo actions
Implement test coverage

### LINKED ISSUE #2056: Test Drag & Drop
Implement test coverage

### LINKED ISSUE #2057: Full test NFTs
Implement test coverage

### LINKED ISSUE #2058: Test filter by asset function (search)
Implement test coverage

### LINKED ISSUE #2059: Test favorites function
Implement test coverage

### LINKED ISSUE #2060: Test that the builder in world components (lock, name) work properly
Move responsibility outside of BuilderInWorldController

### LINKED ISSUE #2064: BuilderInWorldController: SceneObject creation
Move responsibility outside of BuilderInWorldController

### PR DESCRIPTION
**Pull request by D4rWiNSS**
closes #2060 
closes #2059 
closes #2059 
closes #2056 
closes #2057 
closes #2055
closes #2058 
closes #2038 
closes #1991 
closes #1999 
closes #1996 
closes #2045 
closes #2064
closes #2049
closes #2048
closes #2047
closes #2046

# What? 
This PR includes some biw unit test (favorites, quick bar, catalog, smart item component), the entity images for smart item components, and some bug fixes.

There is also segregation of responsibilities of `BuilderInWorldController`. Now the responsibilities are separated by controllers so we have a clearer structure of how biw works

### CODE REVIEW

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/BIWCatalogManager.cs [hunk 1]
```diff
@@ -9,17 +9,16 @@
 public static class BIWCatalogManager
 {
     public static bool VERBOSE = false;
-    private static bool INIT = false;
+    private static bool IS_INIT = false;
 
     public static void Init()
```
Comment (BrianAmadori) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/BIWCatalogManager.cs:14]: Two concerns:

1. We have an `Init()` without a `Dispose()` here. 
2. If this class needs to track state (as intended with the use of `IS_INIT`) we should make it an instance class. Otherwise we risk having a bad state on test execution time.

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs [hunk 2]
```diff
@@ -62,16 +63,20 @@ private void Start()
...
-        HUDController.i.builderInWorldMainHud.OnDeleteSelectedAction += DeleteSelectedEntitiesInput;
-        HUDController.i.builderInWorldMainHud.OnEntityClick += ChangeEntitySelectionFromList;
-        HUDController.i.builderInWorldMainHud.OnEntityLock += ChangeEntityLockStatus;
-        HUDController.i.builderInWorldMainHud.OnEntityChangeVisibility += ChangeEntityVisibilityStatus;
-        HUDController.i.builderInWorldMainHud.OnEntityRename += SetEntityName;
-        HUDController.i.builderInWorldMainHud.OnEntitySmartItemComponentUpdate += UpdateSmartItemComponentInKernel;
+        base.Init();
+        if (HUDController.i.builderInWorldMainHud != null)
+        {
+            HUDController.i.builderInWorldMainHud.OnEntityDelete += DeleteSingleEntity;
```
Comment (BrianAmadori) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs]: Maybe we can store the `HUDController.i.builderInWorldMainHud` in a local variable to increase legibility.

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWActionsShould.cs [hunk 3]
```diff
@@ -0,0 +1,190 @@
+using DCL;
+using DCL.Helpers;
+using NUnit.Framework;
+using System.Collections;
+using System.Collections.Generic;
+using UnityEngine;
+using UnityEngine.TestTools;
+
+public class BIWActionsShould : IntegrationTestSuite_Legacy
```
Comment (BrianAmadori) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWActionsShould.cs:11]: Can we try to use the non-legacy `IntegrationTestSuite` here? We should avoid creating new tests with the legacy class. If this causes some issues we can do some pair programming here.

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/BIWCatalogManager.cs (hunk 1 above)
Comment (D4rWiNSS) [reply unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/BIWCatalogManager.cs:14]: This class was originally a singleton , I moved to a static class because of our conventions to get rid of singletons. 

However, this class should live as long as the app is running since it will handle all the catalog/collectibles changes.

If we want to have a `Dispose()` method and make this class an instance class, we should refactor it to handle all the content from catalog/collectibles each time that initialize and init it each time with the builder in world which can have some performance trade-off. 

We can add a technical debt issue if you want

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs (hunk 2 above)
Comment (D4rWiNSS) [reply unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs]: Done, however, we need to take into account that if we recreate the UI somehow we lose the reference

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWActionsShould.cs (hunk 3 above)
Comment (D4rWiNSS) [reply unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Tests/BIWActionsShould.cs:11]: Sure, I tried with the new system but had a couple of problems, since you were on PTO I just swapped to legacy but we ca go for the new ones!

**Review by pravusjif — APPROVED** [review]

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs (hunk 2 above)
Comment (AjimenezDCL) [reply unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs]: We could use a field for that:
`private BuilderInWorldMainHUD biwMainHUD => HUDController.i.builderInWorldMainHud`

Besides increasing readability, it's a good practice to follow to ease the process of searching for references.

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBar/QuickBarController.cs [hunk 4]
```diff
@@ -15,10 +15,20 @@ public QuickBarController(QuickBarView view)
         view.OnQuickBarAdd += SetQuickBarShortcut;
     }
 
-    public void QuickBarObjectSelected(int index)
+    public int GetSlotsCount()
+    {
+        return AMOUNT_OF_QUICK_SLOTS;
+    }
```
Comment (AjimenezDCL) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBar/QuickBarController.cs:21]: Cannot we just make the const public and avoid this method?

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWCreatorController.cs [hunk 5]
```diff
@@ -0,0 +1,249 @@
...
+using System;
+using System.Collections;
+using System.Collections.Generic;
+using UnityEngine;
+
+public class BIWCreatorController : BIWController
+{
+    public BIWModeController biwModeController;
+    public BIWFloorHandler biwFloorHandler;
+    public BuilderInWorldEntityHandler builderInWorldEntityHandler;
```
Comment (AjimenezDCL) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWCreatorController.cs:16]: If they are public only for the purpose to have dragged references in the editor, we should use the `SerializeField` attribute and make them private.

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs [hunk 6]
```diff
@@ -0,0 +1,109 @@
...
+    private void Start()
+    {
+        meshLoadIndicator.SetCamera(Camera.main);
+    }
+
+    public void Clean()
+    {
+        foreach (GameObject gameObject in floorPlaceHolderDict.Values)
+        {
+            GameObject.Destroy(gameObject);
```
Comment (AjimenezDCL) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs:36]: Shouldnt we clear the dictionary or at least put the values to `null`?

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWInputHandler.cs [hunk 7]
```diff
@@ -0,0 +1,218 @@
...
+    [Header("Design variables")]
+    public float msBetweenInputInteraction = 200;
+
+    [Header("References")]
+    public BuilderInWorldController builderInWorldController;
+    public ActionController actionController;
+    public BIWModeController biwModeController;
+    public BuilderInWorldInputWrapper builderInputWrapper;
+    public BIWOutlinerController outlinerController;
+    public BuilderInWorldEntityHandler builderInWorldEntityHandler;
```
Comment (AjimenezDCL) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWInputHandler.cs:18]: Unless we need them to be public, we should make them `[SerializeField] private`

**Review by AjimenezDCL — APPROVED** [review]
I know this has been approved already, take a look at my suggesitons and let's open a small CR branch for it.
