### PR TITLE
fix: Weird behaviour on the chat notifications

### LINKED ISSUE #976: Weird behaviour on the chat notifications
## Bug description
There are sometimes when we receive a new public message on the world chat, the notification badge is increasing its number even if there was not any other window open.

## How to reproduce it?
It has been reproduced only in some computers:

1. Close all taskbar windows (Friends window and all private chats).
2. Wait for receive some public message in the world chat.
3. Notice that the notification badge has been increased.

## Expected behaviour
The notification badge should only be increased only when Friends window or a private chat window is open.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
# What? 
There are sometimes when we receive a new public message on the world chat, the notification badge is increasing its number even if there was not any other window open.

**More details:** [https://github.com/decentraland/explorer/issues/976](https://github.com/decentraland/explorer/issues/976)

### CODE REVIEW

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs [hunk 1]
```diff
@@ -22,6 +22,8 @@ public class PrivateChatWindowHUDView : MonoBehaviour
     public event System.Action OnClose;
     public UnityAction<ChatMessage> OnSendMessage;
 
+    public string UserId { get; internal set; }
```
Comment (pravusjif) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs]: silly change: this should be `userId`

**Review by pravusjif — APPROVED** [review]
let's update that variable name and we can merge

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs]: Done! Thanks.
