### PR TITLE
fix: pressing ESC key send chat messages when it shouldn't

### LINKED ISSUE #875: bug: pressing ESC key send chat messages when it shouldn't
When pressing ESC while some text is written on the chat input, UI element doesn't get de-focused, causing WASD input getting recorded and sent when enter is pressed again.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
# What? 
When pressing ESC while some text is written on the chat input, UI element doesn't get de-focused, causing WASD input getting recorded and sent when enter is pressed again.

### CODE REVIEW

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs [hunk 1]
```diff
@@ -25,7 +27,17 @@ public static ChatHUDView Create()
...
         this.controller = controller;
-        inputField.onSubmit.AddListener(onSendMessage);
+        onSendMessageAction = onSendMessage;
+        inputField.onSubmit.AddListener(OnInputFieldSubmit);
+    }
+
+    private void OnInputFieldSubmit(string message)
+    {
+        // A TMP_InputField is automatically marked as 'wasCanceled' when the ESC key is pressed
+        if (inputField.wasCanceled)
```
Comment (BrianAmadori) [inline unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs:37]: We should add a test to cover this behaviour

**Review by BrianAmadori — CHANGES_REQUESTED** [review]

File: unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs:37]: Test added!

**Review by BrianAmadori — APPROVED** [review]

**Review by pravusjif — APPROVED** [review]
