### PR TITLE
fix: analytics config override always to avoid sending prod data

### LINKED ISSUE #71: Ensure that we never use a production setting for Segment
This is high priority:

- Diego has realized that sometimes using feature branches previews (`/branch/....`) we are combining that with the `?ENV=org` setting, which causes segment to report inaccurate data about our numbers

- We should make sure that whatever mechanism we use, we are not polluting the DB.

A possible approach could be to modify `queueTrackingEvent` to check that the `window.location` value is actually `explorer.decentraland.org` before sending prod data.

### PR DESCRIPTION
**Pull request by eordano**
Fixes #71

### CODE REVIEW

File: kernel/packages/shared/index.ts [hunk 1]
```diff
@@ -43,7 +43,10 @@ function initializeAnalytics() {
   const TLD = getTLD()
   switch (TLD) {
     case 'org':
-      return initialize('1plAT9a2wOOgbPCrTaU8rgGUMzgUTJtU')
+      if (window.location.host === 'explorer.decentraland.org') {
```
Comment (moliva) [inline kernel/packages/shared/index.ts:51]: This might need to be revisited in the future as I understand we will need to use other hosts as well depending on the region.

**Review by moliva — APPROVED** [review]

**Comment by moliva** [comment]
Review #74 along with this to improve code legibility.

**Comment by eordano** [comment]
Beautiful thanks!
