### PR TITLE
fix: TextShape now implements visible and opacity correctly

### LINKED ISSUE #1392: TextShape opacity property doesn't work
The TextShape component has an "opacity" property that should let you make a text semi-transparent. However, if you change that value nothing happens, and there is no other way to make a text semi-transparent.

The following code produces a text that is still 100% opaque
```ts
  const message = new Entity();
  message.addComponent(new TextShape("Test");
  message.addComponent(
    new Transform({ position: new Vector3(8, 1, 8) })
  );
  message.getComponent(TextShape).opacity = 0.5;
engine.addEntity(message)
```

### PR DESCRIPTION
**Pull request by AjimenezDCL**
#827

The problem is `TextShape` in Unity not extending `BaseShape` where this property exists. This is problematic for various reasons:
- `TextShape` currently is a `BaseComponent` in Unity, that means that changing the parent class to `BaseShape` (which is a Disposable component) can get really messy.
- Another side effect of making `TextShape` a `BaseShape` are the properties `withCollision` and `isPointerBlocker`. After discussing it with Nico, these two are enabled by default in kernel, which means that the current deployed scenes using `TextShape` has these properties already set by default to `true`. If we implement said properties in Unity we might be introducing a gamebreaking change.

On a side note, this ticket will also fix #1392

### CODE REVIEW

**Review by BrianAmadori — APPROVED** [review]
Looks good!

File: unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs [hunk 1]
```diff
@@ -86,7 +88,7 @@ public static IEnumerator ApplyModelChanges(ParcelScene scene, TMP_Text text, Mo
 
             text.text = model.value;
 
-            text.color = new Color(model.color.r, model.color.g, model.color.b, model.color.a);
+            text.color = new Color(model.color.r, model.color.g, model.color.b, model.visible ? model.opacity : 0);
```
Comment (marcosnc) [inline unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:91]: Why are we using `model.opacity` now instead of `model.color.a`?

File: kernel/packages/decentraland-ecs/src/decentraland/Components.ts [hunk 2]
```diff
@@ -639,6 +639,9 @@ export class TextShape extends Shape {
   @ObservableComponent.field
   billboard: boolean = false
 
+  @ObservableComponent.field
+  visible: boolean = false
```
Comment (nchamo) [inline kernel/packages/decentraland-ecs/src/decentraland/Components.ts]: Why is the default `false`, if it was previously `true`?

File: unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs (hunk 1 above)
Comment (AjimenezDCL) [reply unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:91]: In `kernel` we are combining `Color3 color` and `float opacity` but Unity has no implementation of Color3, all of them has alpha (we could implement our own Color3, but it's a bit overkill) . So basically color.a does nothing because the value is defaulted.

We have two ways to solve this:
1) Remove opacity and use a Color4
2) Maintain opacity and use it in Unity instead of color.a.

After talking with Nico we decided that the second one was less disruptive for the creators.

File: kernel/packages/decentraland-ecs/src/decentraland/Components.ts (hunk 2 above)
Comment (AjimenezDCL) [reply kernel/packages/decentraland-ecs/src/decentraland/Components.ts]: Because I am stupid =D, nice catch

**Review by nchamo — APPROVED** [review]
Great work!
